# Generated by Django 5.1.1 on 2024-10-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_fournisseur_product_stock_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseurproduit',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
