# Generated by Django 5.1.1 on 2024-10-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_fournisseurproduit_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
